package com.pomaskin.weather.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006397)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D31)
val md_theme_light_secondary = Color(0xFF865300)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDDB9)
val md_theme_light_onSecondaryContainer = Color(0xFF2B1700)
val md_theme_light_tertiary = Color(0xFF006D37)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF6BFE9C)
val md_theme_light_onTertiaryContainer = Color(0xFF00210C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72787E)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFF92CCFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006397)
val md_theme_light_outlineVariant = Color(0xFFC2C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF92CCFF)
val md_theme_dark_onPrimary = Color(0xFF003351)
val md_theme_dark_primaryContainer = Color(0xFF004B73)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_secondary = Color(0xFFFFB961)
val md_theme_dark_onSecondary = Color(0xFF472A00)
val md_theme_dark_secondaryContainer = Color(0xFF663E00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDDB9)
val md_theme_dark_tertiary = Color(0xFF4AE183)
val md_theme_dark_onTertiary = Color(0xFF003919)
val md_theme_dark_tertiaryContainer = Color(0xFF005228)
val md_theme_dark_onTertiaryContainer = Color(0xFF6BFE9C)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CE)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF006397)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF92CCFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF3498DB)
